# native configuration (for local development):

crypto:
  order:
    features:
      enable-fill-or-kill: true
      enable-immediate-or-cancel: true
      enable-post-only: true
      enable-hidden: true
      enable-stop: true
      enable-stop-limit: true
      enable-trailing-stop: true
  setting:
    fee:
      default-maker-rate: 0.001
      default-taker-rate: 0.002
      always-charge-quote: true
    mining:
      enabled: true
      currency: CFC
      total: 5000000
      percent: 1.0
    divident:
      enabled: true
      minimum: 100
      percent: 1.0

# logging config:
logging:
  level:
    com.itranswarp.warpdb.WarpDb: DEBUG
