# init vars by executing command
# vars:
#   timestamp: string like "2018-01-02_17_20_59", used for deploy id.
#   xmx: string like "1024" for maximum MB used for JVM.

---

- name: init var_timestamp by executing command
  shell: date +%Y-%m-%d_%H_%M_%S
  register: var_timestamp

- name: set var "timestamp"
  set_fact:
    timestamp: "{{ var_timestamp.stdout }}"

- name: print var "timestamp"
  debug:
    msg: "timestamp = {{ timestamp }}"

- name: set var "deploy_type"
  set_fact:
    deploy_type: "{{ apps[app].deploy_type }}"

- name: print var "deploy_type"
  debug:
    msg: "deploy_type = {{ deploy_type }}"

# calculate the maximum memory used by JVM: xmx = MAX(total * 0.75, total - 800MB)

- name: init memory size
  shell: grep MemTotal /proc/meminfo | awk '{x=int($2/1024*0.75);y=int($2/1024-800);print (x<y?y:x)}'
  register: var_xmx

- name: set var "xmx"
  set_fact:
    xmx: "{{ var_xmx.stdout }}"

- name: print var "xmx"
  debug:
    msg: "xmx = {{ xmx }}"
