# deploy rocketmq

---

- name: remove old binary
  file:
    path: /srv/rocketmq
    state: absent

- name: re-create rocketmq dir
  file:
    path: /srv/rocketmq
    state: directory

- name: download rocketmq binary
  get_url:
    url: http://www-us.apache.org/dist/rocketmq/4.2.0/rocketmq-all-4.2.0-bin-release.zip
    dest: /home/ubuntu/rocketmq.zip
    checksum: sha1:ec0e8f874b87220d69e189257db8c09d1c7a6840

- name: install unzip
  apt:
    name: unzip

- name: unarchive rocketmq binary
  unarchive:
    src: /home/ubuntu/rocketmq.zip
    dest: /srv/rocketmq/
    remote_src: yes

- name: copy conf dir
  copy:
    src: environments/{{ profile }}/rocketmq/conf
    dest: /srv/rocketmq

- name: make data dir for rocketmq
  file:
    path: /data/rocketmq/store
    state: directory
    owner: www-data
    group: www-data
